properties([parameters([string(defaultValue: "1.3.9", description: 'CLI Version', name: 'cli_version'), choice(name: 'zone_id', choices: ['defaultzone', 'rroum', 'DIOuN'], description: 'Zone Identifier (1. Static or 2. Dynamic or 3. Docker)'), string(defaultValue: "https://dockerps3.apps.neotys.com:8080", description: 'NeoLoad Web Api Url', name: 'api_url'), string(defaultValue: "nwilliams_TC", description: 'Unique Test Case Name', name: 'test_name')])])

node('dockerps3_host') {
  stage('Install the NLWeb CLI') {
    sh """python3 --version
          pip3 --version
          sudo pip3 install neoload==${cli_version}
          neoload --version"""
  }
  stage('Login to the NLWeb CLI') {
    withCredentials([string(credentialsId: 'NLW_TOKEN', variable: 'NLW_TOKEN')]) {
      sh "neoload login --url ${api_url} --ssl-cert False $NLW_TOKEN"
    }
  }
  stage('Checkout the NL project') {
    checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'neoload-project-${BUILD_NUMBER}']], userRemoteConfigs: [[credentialsId: 'theqmguy', url: 'https://github.com/theqmguy/neoload-ci-training.git']]])
  }
  stage('Create the NLWeb Test') {
    sh """neoload workspaces use 'Default Workspace' \
          test-settings --zone ${zone_id} --lgs 1 --scenario sanityScenario --description 'Do NOT Delete (Build ${BUILD_NUMBER})' createorpatch ${test_name} \
          project --path "$WORKSPACE/neoload-project-${BUILD_NUMBER}/tests/neoload_projects/example_1/" upload ${test_name}"""
  }
  stage('Execute the NLWeb Test') {
    sh """neoload run \
          --return-0 \
          --web-vu 20 \
          ${test_name}"""
  }
  stage('Publish Results to Jenkins') {
    sh """neoload test-results junitsla"""
    sh "sed -i 's/\\<br\\/\\>/\\n/g' junit-sla.xml"
    junit 'junit-sla.xml'
  }
  stage('Uninstall the NLWeb CLI') {
    sh """sudo pip3 uninstall --yes neoload==1.3.9"""  
  }
}
